### PR TITLE
LPS-77010 Document Form events and properties

### PR DESCRIPTION
**Pull request by brunobasto**
#Hey @jbalsas, 

/cc @juliocamarero @marcellustavares @leoadb @sergiogonzales @adolfopa @epgarcia

Here's a follow up PR after the talk I had with Marcellus, Eduardo and Julio. We decided that we should keep generic tracking of Forms in this client. I'm sending together with this PR, a proposal for naming events and properties and an initial documentation for the form events.

You will notice that I have the ```formViewed``` event. And I'm sending this for every form on the page once the page loads. We need that because we don't have a way to know when a generic form (like a hubspot form) is on the page. The page view event is not enough.
You and me talked about it and we know this is not the best way to make sure the user actually viewed the form, but I'm hoping we can move on smaller interactions and improve that later. We can annotate some forms as not trackable or implement logic to check if the form has actually been viewed.

One other requirement that came to me was to add the ```focusDuration```on the ```fieldBlurred```event. This is a metric we need to gather and tracking this on the client side will prevent handling some edge cases on the backend. @marcellustavares can explain in more details that part.

Let me know if you have any questions. Thx

### CODE REVIEW

**Comment by marcellustavares** [comment]
@jbalsas, let me know if you have any questions.

Thanks

**Comment by jbalsas** [comment]
Hey @marcellustavares, sorry, I'm in LA this week which gives me very little time to review. I took a quick look on monday and this looks good in general, but I wanted the chance to give it a more thorough review before the end of the week.

If you need to push it through, I can do a quick scan and we can come back to fix any issues we might find later.

**Comment by marcellustavares** [comment]
thanks for the update @jbalsas, Bruno just mentioned that you were in meetings during this week in LA :) don't worry, we can eventually push this task to next week.

**Comment by jbalsas** [comment]
Hey @brunobasto, @marcellustavares, I assumed you guys would've already merged this in. Do you still want me to go over this and send it to the repo?

**Comment by brunobasto** [comment]
Hey @jbalsas, if you have any feedbacks, please feel free to post them here. I'll go over it today, to see what I can improve. Mainly I'm concerned about tracking hidden or unnecessary forms. One idea was to add either a whitelist of forms to be tracked or a blacklist of forms not to be tracked. And I imagine it would be added to the form node itself as a data attribute of some kind.

**Comment by jbalsas** [comment]
Looks good to me, you guys push through!

**Pull request closed without merging**
